Content/Art/Environment/SM_Bar_01a/SM_Bar_01a.uasset
Content/Art/Environment/SM_Bar_01a/T_Bar_01a_C.uasset
Content/Art/Environment/SM_Bar_01a/T_Bar_01a_N.uasset
Content/Art/Environment/SM_Bar_01a/T_Bar_01a_ORM.uasset
Content/Art/Material_Instances/MI_Bar_01a.uasset

Note:
Shading error, UVs and Topology needs to be revisited.

Added SM_Bar_01a Asset into the engine

---

Config/DefaultGame.ini

StartupMovieImplemented

---

Content/Art/UI/HUD/Ember_Frames/HUD_Ember1.uasset
Content/Art/UI/HUD/Ember_Frames/HUD_Ember10.uasset
Content/Art/UI/HUD/Ember_Frames/HUD_Ember11.uasset
Content/Art/UI/HUD/Ember_Frames/HUD_Ember12.uasset
Content/Art/UI/HUD/Ember_Frames/HUD_Ember13.uasset
Content/Art/UI/HUD/Ember_Frames/HUD_Ember14.uasset
Content/Art/UI/HUD/Ember_Frames/HUD_Ember2.uasset
Content/Art/UI/HUD/Ember_Frames/HUD_Ember3.uasset
Content/Art/UI/HUD/Ember_Frames/HUD_Ember4.uasset
Content/Art/UI/HUD/Ember_Frames/HUD_Ember5.uasset
Content/Art/UI/HUD/Ember_Frames/HUD_Ember6.uasset
Content/Art/UI/HUD/Ember_Frames/HUD_Ember7.uasset
Content/Art/UI/HUD/Ember_Frames/HUD_Ember8.uasset
Content/Art/UI/HUD/Ember_Frames/HUD_Ember9.uasset
Content/Art/UI/PauseMenu/Pause_FrameOverlay.uasset
Content/Art/UI/PauseMenu/Pause_PauseTitle.uasset
Content/Art/UI/PauseMenu/Pause_SelectedLine.uasset

Maya pause menu

---

Content/Art/Characters/Enemies/WesternBoss/Animations/Anim_BossHeavyAttack.uasset
Content/Art/Characters/Enemies/WesternBoss/Materials/accessories.uasset
Content/Art/Characters/Enemies/WesternBoss/Materials/accessories_ncl1_1.uasset
Content/Art/Characters/Enemies/WesternBoss/Materials/lambert4.uasset

Added Boss skeletal mesh and animations
also added shooter run

Animations and Boss

---

Content/Art/Characters/Enemies/WesternBoss/Animations/Anim_BossLightAttack.uasset

Added Light Attack for Boss

---

Content/Art/Environment/Train/TrainStorageModKit/SM_TrainDoor.uasset

Door Texture

---

Content/Art/VFX/NS_KickSlash/BP_GroundSlash.uasset
Content/Art/VFX/NS_KickSlash/M_Mat01.uasset
Content/Art/VFX/NS_KickSlash/M_Mat02.uasset
Content/Art/VFX/NS_KickSlash/Material.uasset
Content/Art/VFX/NS_KickSlash/Mi_Mat01_Inst.uasset
Content/Art/VFX/NS_KickSlash/Mi_Mat02_Inst.uasset
Content/Art/VFX/NS_KickSlash/NS_GroundSlash.uasset
Content/Art/VFX/NS_KickSlash/SM_GroundSlashImproved.uasset
Content/Art/VFX/NS_KickSlash/T_GradientHorizontal.uasset
Content/Art/VFX/NS_KickSlash/debris_Cube_cell_001.uasset
Content/Art/VFX/NS_KickSlash/debris_Cube_cell_002.uasset
Content/Art/VFX/NS_KickSlash/debris_Cube_cell_004_cell_003.uasset

imported the slash file and supporting actors/textures

Kick slash imported hayden

---

Content/Art/VFX/NS_BaseSlashTrail/M_TestSlash.uasset
Content/Art/VFX/NS_BaseSlashTrail/Mi_TestSlash_Inst.uasset
Content/Art/VFX/NS_BaseSlashTrail/NS_DefaultSlash.uasset
Content/Art/VFX/NS_BaseSlashTrail/swoosh2.uasset

placeholder ribbon renderer with sample placeholder texture

imported ribbon renderer

---

Content/Art/Characters/Enemies/Heavy/Animations/Sequence/Anim_HeavyAttack.uasset

Heavy Enemy Attacks

---

Content/Art/Environment/Horror/MessHall/Campfire.uasset
Content/Art/Environment/Horror/MessHall/CanoeProxy.uasset
Content/Art/Environment/Horror/MessHall/SM_CanoeHolder.uasset
Content/Art/Environment/Horror/MessHall/SM_Canoe_01.uasset
Content/Art/Environment/Horror/MessHall/SM_Rug_01.uasset
Content/Art/Environment/Horror/MessHall/SM_Rug_02.uasset

canoe, canoe holder, square rug, large rectangle rug, campfire

Maya proxy

---

Content/Art/Characters/Enemies/Heavy/Animations/Sequence/Anim_HeavyIdle.uasset
Content/Art/Characters/Enemies/WesternBoss/Animations/Seq/Anim_BossDamage.uasset
Content/Art/Characters/Enemies/WesternBoss/Animations/Seq/Anim_BossStun.uasset

Added Damage and Stun for Boss and Idle for Heavy

Heavy and Boss Animations added

---

Content/Art/Characters/Syd/Apron1.uasset
Content/Art/Characters/Syd/SK_SydRig.uasset
Content/Art/Characters/Syd/SK_SydRig_Anim.uasset
Content/Art/Characters/Syd/SK_SydRig_PhysicsAsset.uasset
Content/Art/Characters/Syd/SK_SydRig_Skeleton.uasset
Content/Art/Characters/Syd/standardSurface3.uasset

Base test rig for Syd (checking how much weight painting is needed for apron)

Added Test Syd Rig

---

Content/Art/VFX/MAT_Textures/NS_StylizedSmoke.uasset
Content/Art/VFX/NS_BottleDebris.uasset
Content/Art/VFX/NS_Punch.uasset

Reverts AndrewSwanstrom/ReelRun#542

Revert "New vf xfr"

---

Content/Art/Characters/Betsy/Animation/NewMontage/Anim_DakotaDash.uasset

Dakota Dash Base

---

Content/Art/Characters/Syd/SK_SydRig.uasset
Content/Art/Characters/Syd/SK_SydRig_Anim.uasset

Syd Sizing

---

Content/Art/Characters/Syd/Animations/Sequences/Anim_SydIdle.uasset
Content/Art/Characters/Syd/SK_SydRig.uasset

fixed some weights and added idle

Syd Begins

---

Content/Art/Characters/Syd/SK_SydRig.uasset

Syd Update

---

Content/Art/Characters/Syd/Animations/Sequences/Anim_SydIdle.uasset
Content/Art/Characters/Syd/SK_SydRig.uasset

syd fixed (again)

---

Content/Art/Characters/Syd/Animations/Sequences/Anim_SydWalk.uasset
Content/Art/Characters/Syd/Animations/Sequences/Anim_SydWalkEnd.uasset
Content/Art/Characters/Syd/Animations/Sequences/Anim_SydWalkStart.uasset

he do be stompin

---

Content/Art/BlockoutMeshes/SM_BL_Curtains.uasset
Content/Art/BlockoutMeshes/SM_BL_Mic.uasset
Content/Art/BlockoutMeshes/SM_BL_ParCanLight.uasset
Content/Art/BlockoutMeshes/SM_BL_RomanceTables.uasset
Content/Art/BlockoutMeshes/SM_BL_VaseCandles.uasset
Content/Art/BlockoutMeshes/SM_SM_BL_RomanceTables.uasset
Content/Levels/LV_RomanceAct1.umap
Content/Levels/LV_RomanceAct2.umap
Content/Levels/_GENERATED/braya/CubeGridToolOutput_ADD171FE.uasset
Content/Levels/_GENERATED/braya/CubeGridToolOutput_E803B05A.uasset

- Blockout Romance Act 2
- Update Outline Organization for Act1
- Pre Lit Act 2

Romance Act 2 Romance

---

Content/Art/Characters/Syd/Animations/Sequences/Anim_SydDash.uasset
Content/Art/Characters/Syd/Animations/Sequences/Anim_SydLightAttackSequence.uasset

light base sequence and dash
(adding individual attacks later)

Syd Animations in

---

Content/Art/Environment/Horror/Clutter/Outside/SM_Backpack.uasset
Content/Art/Environment/Horror/Clutter/Outside/SM_BeerCan.uasset
Content/Art/Environment/Horror/Clutter/Outside/SM_BigTrashcan.uasset
Content/Art/Environment/Horror/Clutter/Outside/SM_FishingBucket.uasset
Content/Art/Environment/Horror/Clutter/Outside/SM_FishingNet.uasset
Content/Art/Environment/Horror/Clutter/Outside/SM_FishingRod.uasset
Content/Art/Environment/Horror/Clutter/Outside/SM_Paddle.uasset
Content/Art/Environment/Horror/Clutter/Outside/SM_Radio.uasset
Content/Art/Environment/Horror/Clutter/Outside/SM_SleepingBag.uasset
Content/Art/Environment/Horror/Clutter/Outside/SM_SpamCan.uasset

missing chips
cemetary cluttter
radio shack clutter

Outside Clutter

---

Content/Art/Characters/Syd/Animations/Sequences/Anim_SydHeavyAttackSequence.uasset

will be cut up later pls i don't wanna look at this

base syd heavy animation

---

Content/Art/Environment/Horror/Clutter/Cemetery/SM_FlowerVase.uasset
Content/Art/Environment/Horror/Clutter/Cemetery/SM_FramedPhoto.uasset
Content/Art/Environment/Horror/Clutter/Cemetery/SM_IncenseHolder.uasset
Content/Art/Environment/Horror/Clutter/Cemetery/SM_IncensePot.uasset

-just use foliage flowers to lay them on some graves

Cemetery Clutter

---

Content/Art/Characters/Enemies/HorrorBoss/SK_HorrorBoss.uasset
Content/Art/Characters/Enemies/HorrorBoss/SK_HorrorBoss_PhysicsAsset.uasset
Content/Art/Characters/Enemies/HorrorBoss/SK_HorrorBoss_Skeleton.uasset

Horror boss added

---

Content/Art/Characters/Syd/Animations/Sequences/Anim_SydDamage.uasset

he take damage

---

Content/Art/Environment/Saloon/LevelSequencers/LS_BruteDoor.uasset
Content/Art/Environment/Saloon/LevelSequencers/LS_BruteDoor2.uasset
Content/Art/Environment/Saloon/SM_MirroredSaloonDoors_01.uasset
Content/Levels/WesternLevel.umap

Back added to Brute doors
The right saloon door now shows it's overlay properly

polish of brute doors and saloon door

---

Content/Art/UI/HorrorIntroTransition.uasset
Content/Art/UI/HorrorOutroTransition.uasset
Content/Art/UI/RomanceAct1Intro.uasset
Content/Art/UI/RomanceAct2Intro.uasset
Content/Art/UI/RomanceAct3Intro.uasset
Content/Art/UI/RomanceEnd.uasset

Upload transition textures for horror and romance.

Transition Textures

---

Content/Art/Environment/Romance/LevelSequencers/LS_Act1Sequencer.uasset
Content/Levels/LV_RomanceAct1.umap

set up level sequencer that plays an intro at the beginning of romance act 1

level sequence act 1 romance intro

---

Content/Art/Environment/Romance/LevelSequencers/Act2Sequencers/LS_RomanceAct2Intro.uasset
Content/Art/Environment/Romance/LevelSequencers/Act2Sequencers/LS_RomanceAct2Wave2.uasset
Content/Art/Environment/Romance/LevelSequencers/Act2Sequencers/LS_RomanceAct2Wave3.uasset
Content/Art/Environment/Romance/LevelSequencers/LS_Act2Intro.uasset
Content/Levels/LV_RomanceAct2.umap
Content/Levels/LV_RomanceAct3.umap

- added 3 waves to romance act 2
- fixed compile error in romance act 3 level BP

romance act 2 waves

---

Content/Art/Environment/Romance/Act2/SM_CafeChair.uasset
Content/Art/Environment/Romance/Act2/SM_CafeSconce.uasset
Content/Art/Environment/Romance/Act2/SM_ParCanLight.uasset
Content/Art/Environment/Romance/Act2/SM_TenSeaterTable.uasset

Chairs, Tables, Sconce, Par Can Light

Act 2 models

---

Content/Levels/LV_RomanceAct1.umap

- Updated destructibles
- Updated smokestacks

Romance Destructible Update

---

Content/Art/Characters/Maria/Animations/Anim_MariaSway.uasset
Content/Art/Characters/Maria/SK_MariaMirandaGuadalupeRosaliaRamirezDeLaOrtiz.uasset
Content/Art/Characters/Maria/SK_MariaMirandaGuadalupeRosaliaRamirezDeLaOrtiz_Skeleton.uasset

Mariaaaa yaaaaa

---

Content/Art/Characters/Accessories/Heavy/SM_HeavyweightBandana.uasset
Content/Art/Characters/Accessories/Heavy/SM_HeavyweightBelt_belt1_low.uasset
Content/Art/Characters/Accessories/Heavy/SM_HeavyweightBelt_beltbuck_low.uasset
Content/Art/Characters/Accessories/Heavy/SM_HeavyweightHat.uasset
Content/Art/Characters/Accessories/Heavy/accessories1.uasset
Content/Art/Characters/Accessories/Heavy/lambert3.uasset
Content/Art/Characters/Accessories/Light/SM_LightweightBelt_belt1_low2.uasset
Content/Art/Characters/Accessories/Light/SM_LightweightBelt_beltbuck_low2.uasset
Content/Art/Characters/Accessories/Light/SM_LightweightHat.uasset
Content/Art/Characters/Accessories/Light/SM_LightweightMoustache.uasset
Content/Art/Characters/Accessories/Light/accessories1.uasset
Content/Art/Characters/Accessories/Light/lambert3.uasset
Content/Art/Characters/Accessories/Shooter/SM_ShooterBandana.uasset
Content/Art/Characters/Accessories/Shooter/SM_ShooterBelt_belt1_low1.uasset
Content/Art/Characters/Accessories/Shooter/SM_ShooterBelt_beltbuck_low1.uasset
Content/Art/Characters/Accessories/Shooter/SM_ShooterHat.uasset
Content/Art/Characters/Accessories/Shooter/accessories1.uasset
Content/Art/Characters/Accessories/Shooter/lambert3.uasset

Accessories

---

Content/Art/UI/HUD/RadioHUD.uasset
Content/Art/UI/HUD/RadioStatic.uasset

will implement an animation with static when it's on HUD

RadioHUD and Static
